import * as fs from 'fs';
import * as path from 'path';
import { AppTestResult } from './TestResult';

/**
 * Custom HTML Report Generator
 * Creates a beautiful, modern HTML report similar to the reference design
 */
export class CustomHtmlReporter {
  
  /**
   * Generate a modern HTML report
   * @param results - Array of test results
   * @param outputPath - Path where the HTML report should be saved
   * @param reportTitle - Optional custom title for the report
   */
  static generateReport(results: AppTestResult[], outputPath: string, reportTitle?: string): void {
    const timestamp = new Date().toLocaleString('en-US', { 
      day: '2-digit',
      month: '2-digit', 
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false
    });

    const totalTests = results.length;
    const passedTests = results.filter(r => r.status === 'PASS').length;
    const failedTests = results.filter(r => r.status === 'FAIL').length;
    const successRate = totalTests > 0 ? ((passedTests / totalTests) * 100).toFixed(1) : '0.0';

    // Determine report title based on output path or use custom title
    let title = reportTitle;
    if (!title) {
      if (outputPath.includes('AppStore')) {
        title = 'Adhash Application Available Status';
      } else if (outputPath.includes('PlayStore')) {
        title = 'Adhash Application Available Status';
      } else {
        title = 'Adhash Application Available Status';
      }
    }

    const html = this.generateHtmlContent(
      timestamp,
      totalTests,
      passedTests,
      failedTests,
      successRate,
      results,
      title
    );

    // Ensure directory exists
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    // Write HTML file
    fs.writeFileSync(outputPath, html, 'utf-8');
    console.log(`\n📊 Custom HTML Report generated: ${outputPath}`);
  }

  /**
   * Generate the complete HTML content
   */
  private static generateHtmlContent(
    timestamp: string,
    totalTests: number,
    passedTests: number,
    failedTests: number,
    successRate: string,
    results: AppTestResult[],
    reportTitle: string
  ): string {
    const headerIcon = reportTitle.includes('Apple') ? '🍎' : '📱';

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${reportTitle}</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <style>
        ${this.getStyles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div class="header-icon">${headerIcon}</div>
            <h1>${reportTitle}</h1>
            <p class="timestamp">${timestamp}</p>
        </header>

        <div class="stats-container">
            <div class="stat-card blue">
                <div class="stat-number">${totalTests}</div>
                <div class="stat-label">Total Tests</div>
            </div>
            <div class="stat-card green">
                <div class="stat-icon">✓</div>
                <div class="stat-number">${passedTests}</div>
                <div class="stat-label">Passed</div>
            </div>
            <div class="stat-card red">
                <div class="stat-icon">✗</div>
                <div class="stat-number">${failedTests}</div>
                <div class="stat-label">Failed</div>
            </div>
        </div>

        <div class="success-rate">
            <div class="success-percentage">${successRate}%</div>
            <div class="success-label">Success Rate</div>
        </div>

        <div class="progress-bar-container">
            <div class="progress-bar" style="width: ${successRate}%"></div>
        </div>

        <table class="results-table">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Logo</th>
                    <th>App Name</th>
                    <th>Platform</th>
                    <th>Redirect URL</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                ${this.generateTableRows(results)}
            </tbody>
        </table>

        <footer>
            <p>Generated by Playwright TypeScript Automation Framework</p>
            <p>Powered by Page Object Model (POM) Architecture</p>
        </footer>
    </div>
</body>
</html>`;
  }

  /**
   * Generate table rows for test results
   */
  private static generateTableRows(results: AppTestResult[]): string {
    // Play Store and App Store actual logos as base64
    const playStoreLogo = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBmaWxsPSIjMzRBODUzIiBkPSJNMyAyMC41VjMuNWMwLS4zMS4xNS0uNjEuNDEtLjc5TDE0LjU0IDEybC0xMS4xMyA5LjI5Yy0uMjYtLjE4LS40MS0uNDgtLjQxLS43OXoiLz48cGF0aCBmaWxsPSIjRUE0MzM1IiBkPSJNMTYuNTQgMTAuMDJsLTMuNjMtMi4wNEwzLjQxIDIuNzFjLjE2LS4xLjM0LS4xNi41NC0uMTYuMzEgMCAuNjEuMTEuODYuMzJsOS42MyA1LjQzeiIvPjxwYXRoIGZpbGw9IiNGQkJDMDQiIGQ9Ik0xNi41NCAxMy45OGwtMi4xMS0xLjE4TDMuNDEgMjEuMjljLjE2LjEuMzQuMTYuNTQuMTYuMzEgMCAuNjEtLjExLjg2LS4zMmw5LjYzLTUuNDN6Ii8+PHBhdGggZmlsbD0iIzQyODVGNCIgZD0iTTIwLjQxIDEwLjk4bC0zLjg3LTIuMTdsLTIuMTEgMS4xOGwyLjExIDEuMThsMy44Ny0yLjE3Yy4yNi0uMTUuNDEtLjQzLjQxLS43M3MtLjE1LS41OC0uNDEtLjczeiIvPjwvc3ZnPg==';
    const appStoreLogo = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBmaWxsPSIjMDA3QUZGIiBkPSJNMTIgMkM2LjQ4IDIgMiA2LjQ4IDIgMTJzNC40OCAxMCAxMCAxMCAxMC00LjQ4IDEwLTEwUzE3LjUyIDIgMTIgMnptMCAxOGMtNC40MSAwLTgtMy41OS04LThzMy41OS04IDgtOCA4IDMuNTkgOCA4LTMuNTkgOC04IDh6bS0xLTEzaDJ2Nmgtdi02em0wIDhoMnYyaC0ydi0yeiIvPjxwYXRoIGZpbGw9IiMwMDdBRkYiIGQ9Ik0xMS4yOSAxNS43MWwtLjI5LS4yOWMtLjM5LS4zOS0uMzktMS4wMiAwLTEuNDFsMS40MS0xLjQxYy4zOS0uMzkgMS4wMi0uMzkgMS40MSAwbC4yOS4yOWMuMzkuMzkuMzkgMS4wMiAwIDEuNDFsLTEuNDEgMS40MWMtLjM5LjM5LTEuMDIuMzktMS40MSAweiIvPjwvc3ZnPg==';

    return results.map((result, index) => {
      const statusClass = result.status === 'PASS' ? 'status-pass' : 'status-fail';
      const statusText = result.status === 'PASS' ? 'PASS' : 'FAIL';

      // Platform logo - use actual Play Store and App Store logos
      const platformLogo = result.platform === 'Play Store' ? playStoreLogo : appStoreLogo;
      const platformText = result.platform || 'Unknown';

      // Logo image - if missing, use a placeholder
      const logoHtml = result.logoBase64
        ? `<img src="${result.logoBase64}" alt="${result.appName} logo" class="app-logo" />`
        : `<div class="no-logo-placeholder">
             <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 50 50">
               <rect width="50" height="50" rx="12" fill="#e5e7eb"/>
               <text x="25" y="30" font-family="Arial" font-size="24" fill="#9ca3af" text-anchor="middle">📱</text>
             </svg>
           </div>`;

      // URLs with hyperlinks
      const expectedUrl = result.expectedHref;
      const actualUrl = result.actualHref || 'NOT FOUND';

      // Create clickable links
      const expectedUrlHtml = expectedUrl.startsWith('http')
        ? `<a href="${expectedUrl}" target="_blank" class="url-link">${expectedUrl}</a>`
        : `<code class="url-code">${expectedUrl}</code>`;

      const actualUrlHtml = actualUrl !== 'NOT FOUND' && (actualUrl.startsWith('http') || actualUrl.startsWith('/'))
        ? `<a href="${actualUrl.startsWith('http') ? actualUrl : 'https://play.google.com' + actualUrl}" target="_blank" class="url-link">${actualUrl}</a>`
        : `<code class="url-code">${actualUrl}</code>`;
      
      return `
                <tr>
                    <td>${index + 1}</td>
                    <td>${logoHtml}</td>
                    <td><strong>${result.appName}</strong></td>
                    <td><span class="platform-text">${platformText}</span></td>
                    <td>${expectedUrlHtml}</td>
                    <td><span class="status-badge ${statusClass}">${statusText}</span></td>
                </tr>`;
    }).join('');
  }

  /**
   * Get CSS styles for the report
   */
  private static getStyles(): string {
    return `
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', 'Open Sans', 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #ffcdd2 0%, #ef9a9a 100%);
            min-height: 100vh;
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
            overflow: hidden;
        }

        header {
            background: linear-gradient(135deg, #e57373 0%, #ef5350 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }

        .header-icon {
            font-size: 48px;
            margin-bottom: 10px;
        }

        header h1 {
            font-size: 32px;
            font-weight: 600;
            margin-bottom: 10px;
            letter-spacing: 0.5px;
        }

        .timestamp {
            font-size: 15px;
            opacity: 0.95;
            font-weight: 400;
        }

        .stats-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            padding: 40px;
            background: #f8f9fa;
        }

        .stat-card {
            background: white;
            padding: 30px;
            border-radius: 12px;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease;
        }

        .stat-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 12px rgba(0, 0, 0, 0.15);
        }

        .stat-card.blue {
            border-top: 4px solid #e57373;
        }

        .stat-card.green {
            border-top: 4px solid #66bb6a;
        }

        .stat-card.red {
            border-top: 4px solid #ef5350;
        }

        .stat-icon {
            font-size: 24px;
            margin-bottom: 10px;
        }

        .stat-number {
            font-size: 48px;
            font-weight: 700;
            margin-bottom: 10px;
        }

        .stat-card.blue .stat-number {
            color: #e57373;
        }

        .stat-card.green .stat-number {
            color: #66bb6a;
        }

        .stat-card.red .stat-number {
            color: #ef5350;
        }

        .stat-label {
            font-size: 14px;
            color: #5f6368;
            text-transform: uppercase;
            letter-spacing: 1.2px;
            font-weight: 500;
        }

        .success-rate {
            text-align: center;
            padding: 30px 40px 10px;
        }

        .success-percentage {
            font-size: 64px;
            font-weight: 700;
            color: #66bb6a;
            margin-bottom: 10px;
        }

        .success-label {
            font-size: 16px;
            color: #5f6368;
            text-transform: uppercase;
            letter-spacing: 1.2px;
            font-weight: 500;
        }

        .progress-bar-container {
            margin: 20px 40px 40px;
            height: 30px;
            background: #e5e7eb;
            border-radius: 15px;
            overflow: hidden;
            position: relative;
        }

        .progress-bar {
            height: 100%;
            background: linear-gradient(90deg, #66bb6a 0%, #43a047 100%);
            transition: width 1s ease;
            box-shadow: 0 2px 4px rgba(102, 187, 106, 0.4);
            position: absolute;
            top: 0;
            left: 0;
        }

        .results-table {
            width: 100%;
            border-collapse: collapse;
            margin: 0 0 40px 0;
        }

        .results-table thead {
            background: linear-gradient(135deg, #e57373 0%, #ef5350 100%);
            color: white;
        }

        .results-table th {
            padding: 16px;
            text-align: left;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 13px;
            letter-spacing: 1.2px;
        }

        .results-table tbody tr {
            border-bottom: 1px solid #e5e7eb;
            transition: background-color 0.2s ease;
        }

        .results-table tbody tr:hover {
            background-color: #ffebee;
        }

        .results-table td {
            padding: 16px;
            font-size: 15px;
            color: #37474f;
        }

        .results-table code {
            background: #ffebee;
            padding: 4px 8px;
            border-radius: 4px;
            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
            font-size: 13px;
            color: #37474f;
        }

        .status-badge {
            display: inline-block;
            padding: 6px 16px;
            border-radius: 20px;
            font-weight: 600;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .status-pass {
            background: #c8e6c9;
            color: #2e7d32;
        }

        .status-fail {
            background: #ffcdd2;
            color: #c62828;
        }

        .app-logo {
            width: 50px;
            height: 50px;
            border-radius: 12px;
            object-fit: cover;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .no-logo {
            display: inline-block;
            width: 50px;
            height: 50px;
            background: #e5e7eb;
            border-radius: 12px;
            text-align: center;
            line-height: 50px;
            font-size: 10px;
            color: #9ca3af;
        }

        .no-logo-placeholder {
            display: inline-block;
            width: 50px;
            height: 50px;
        }

        .platform-logo {
            width: 24px;
            height: 24px;
            vertical-align: middle;
        }

        .platform-text {
            font-weight: 600;
            color: #4b5563;
            font-size: 14px;
        }

        .url-link {
            color: #e57373;
            text-decoration: none;
            word-break: break-all;
            font-size: 13px;
        }

        .url-link:hover {
            color: #d32f2f;
            text-decoration: underline;
        }

        .platform-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            background: #f3f4f6;
            font-size: 13px;
            font-weight: 500;
        }

        .url-code {
            font-size: 11px;
            max-width: 200px;
            display: inline-block;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        footer {
            background: #f8f9fa;
            padding: 30px;
            text-align: center;
            color: #6b7280;
            font-size: 14px;
        }

        footer p {
            margin: 5px 0;
        }

        @media (max-width: 768px) {
            .stats-container {
                grid-template-columns: 1fr;
            }

            header h1 {
                font-size: 24px;
            }

            .success-percentage {
                font-size: 48px;
            }

            .results-table {
                font-size: 12px;
            }

            .results-table th,
            .results-table td {
                padding: 10px;
            }
        }
    `;
  }
}

